const categories = ['吃饭','咖啡','打车','用车','衣物','化妆品','娱乐','医疗','其他','礼物']
const icons = {吃饭:'🍜',咖啡:'☕',打车:'🚕',用车:'🚙',衣物:'👕',化妆品:'💄',娱乐:'🎮',医疗:'💊',其他:'📦',礼物:'🎁'}
const SUPABASE_URL='https://cojdriqqlijjsotljmjx.supabase.co'
const SUPABASE_KEY='sb_publishable_xatURVOOWQLOMDax8Muddg_-8G_DGBd'
const SESSION_KEY='xp-ledger-session'
const seed = {
  profile:{name:'攒钱小能手',avatar:''},
  accounts:{微信:1268.50,支付宝:680.20,银行卡:8580.00}, savings:3200,
  budgets:Object.fromEntries(categories.map((c,i)=>[c,[1200,300,400,500,600,400,500,300,300,500][i]])),
  transactions:[
    {id:1,type:'expense',amount:36,category:'吃饭',platform:'微信',date:'2026-07-21',time:'12:26',note:'午饭',repaid:true},
    {id:2,type:'expense',amount:28,category:'咖啡',platform:'美团月付',date:'2026-07-21',time:'09:15',note:'冰美式',repaid:false},
    {id:3,type:'expense',amount:68,category:'打车',platform:'抖音月付',date:'2026-07-20',time:'22:08',note:'回家',repaid:false},
    {id:4,type:'income',amount:8500,category:'工资',platform:'银行卡',date:'2026-07-15',time:'10:00',note:'七月工资',repaid:true},
    {id:5,type:'expense',amount:128,category:'礼物',platform:'支付宝',date:'2026-07-18',time:'19:32',note:'朋友生日',repaid:true}
  ]
}
let state = JSON.parse(localStorage.getItem('xp-ledger-data')||'null') || structuredClone(seed)
state.profile ||= structuredClone(seed.profile)
let session=JSON.parse(localStorage.getItem(SESSION_KEY)||'null')
let page='home', logged=!!session, modal=null, selectedDebt=new Set(), authMode='login', syncTimer=null, syncStatus='已同步', demoMode=false
const app=document.querySelector('#app')
const money=n=>`¥${Number(n).toLocaleString('zh-CN',{minimumFractionDigits:2,maximumFractionDigits:2})}`
const authHeaders=()=>({'apikey':SUPABASE_KEY,'Authorization':`Bearer ${session?.access_token||SUPABASE_KEY}`,'Content-Type':'application/json'})
async function api(path,options={}){let res=await fetch(`${SUPABASE_URL}${path}`,{...options,headers:{...authHeaders(),...options.headers}});let text=await res.text();let body=text?JSON.parse(text):null;if(!res.ok)throw new Error(body?.msg||body?.message||body?.error_description||body?.hint||`请求失败 (${res.status})`);return body}
async function pushCloud(){if(!session?.user?.id)return;syncStatus='同步中…';updateSyncLabel();try{await api('/rest/v1/ledger_data?on_conflict=user_id',{method:'POST',headers:{'Prefer':'resolution=merge-duplicates,return=minimal'},body:JSON.stringify({user_id:session.user.id,data:state,updated_at:new Date().toISOString()})});syncStatus='已同步';updateSyncLabel()}catch(e){syncStatus='同步失败';updateSyncLabel();toast(`云同步失败：${friendlyError(e)}`)}}
async function pullCloud(){let rows=await api(`/rest/v1/ledger_data?user_id=eq.${encodeURIComponent(session.user.id)}&select=data`);if(rows?.[0]?.data){state=rows[0].data;state.profile||=structuredClone(seed.profile);localStorage.setItem('xp-ledger-data',JSON.stringify(state))}else{await pushCloud()}}
function save(){localStorage.setItem('xp-ledger-data',JSON.stringify(state));if(session){syncStatus='等待同步';updateSyncLabel();clearTimeout(syncTimer);syncTimer=setTimeout(pushCloud,350)}}
function updateSyncLabel(){document.querySelectorAll('[data-sync]').forEach(el=>el.textContent=`在线 · ${syncStatus}`)}
function friendlyError(e){let m=e?.message||String(e);if(/Invalid login credentials/i.test(m))return '邮箱或密码不正确';if(/Email not confirmed/i.test(m))return '请先打开验证邮件完成确认';if(/User already registered/i.test(m))return '该邮箱已经注册';if(/Password should be/i.test(m))return '密码至少需要 6 位';if(/Failed to fetch|NetworkError/i.test(m))return '网络连接失败';if(/ledger_data|schema cache/i.test(m))return '请先执行数据库初始化脚本';return m}
const now=()=>new Date().toLocaleTimeString('zh-CN',{hour:'2-digit',minute:'2-digit'})
const today=()=>new Date().toLocaleDateString('sv-SE')
const currentMonth=()=>today().slice(0,7)
const monthLabel=()=>{let [y,m]=currentMonth().split('-');return `${y}年${Number(m)}月`}
const monthTx=()=>state.transactions.filter(t=>t.date.startsWith(currentMonth()))
const expense=()=>monthTx().filter(t=>t.type==='expense').reduce((s,t)=>s+t.amount,0)
const income=()=>monthTx().filter(t=>t.type==='income').reduce((s,t)=>s+t.amount,0)
const debt=()=>state.transactions.filter(t=>t.type==='expense'&&!t.repaid&&(t.platform==='美团月付'||t.platform==='抖音月付'))
const used=c=>monthTx().filter(t=>t.type==='expense'&&t.category===c).reduce((s,t)=>s+t.amount,0)
const totalBudget=()=>Object.values(state.budgets).reduce((a,b)=>a+Number(b),0)
const remainingBudget=()=>totalBudget()-expense()

function login(){let isLogin=authMode==='login';app.innerHTML=`<div class="login-shell"><div class="window login"><div class="titlebar"><span>🔐 ${isLogin?'登录':'注册'}小金库</span><div class="traffic"><span>─</span><span>□</span><span class="close">×</span></div></div><form class="login-welcome" id="authForm"><div class="avatar">🐷</div><h1>小金库</h1><p>${isLogin?'登录后在 Mac 和 iPhone 同步账本':'创建你的私人云端账本'}</p><div class="field" style="text-align:left;margin-top:22px"><label for="email">邮箱</label><input id="email" type="email" autocomplete="email" placeholder="name@example.com" required><label for="password">密码</label><input id="password" type="password" minlength="6" autocomplete="${isLogin?'current-password':'new-password'}" placeholder="至少 6 位密码" required></div><div id="authMessage" class="auth-message hidden"></div><button class="primary" id="loginBtn" style="width:100%;margin-top:18px;padding:10px">${isLogin?'登录':'免费注册'}</button>${isLogin?'<button type="button" class="secondary" id="demoBtn" style="width:100%;margin-top:9px">免登录进入演示</button>':''}<button type="button" class="link-button" id="switchAuth">${isLogin?'第一次使用？创建账号':'已有账号？返回登录'}</button></form></div></div>`;document.querySelector('#switchAuth').onclick=()=>{authMode=isLogin?'register':'login';login()};document.querySelector('#demoBtn')?.addEventListener('click',()=>{demoMode=true;syncStatus='演示模式';state=structuredClone(seed);logged=true;render()});document.querySelector('#authForm').onsubmit=handleAuth}
async function handleAuth(e){e.preventDefault();let email=document.querySelector('#email').value.trim(),password=document.querySelector('#password').value,button=document.querySelector('#loginBtn'),box=document.querySelector('#authMessage');button.disabled=true;button.textContent=authMode==='login'?'正在登录…':'正在注册…';box.classList.add('hidden');try{if(authMode==='login'){let data=await api('/auth/v1/token?grant_type=password',{method:'POST',body:JSON.stringify({email,password})});session={...data,expires_at:Math.floor(Date.now()/1000)+data.expires_in};localStorage.setItem(SESSION_KEY,JSON.stringify(session));logged=true;await pullCloud();render();toast('登录成功，账本已同步 ✓')}else{let data=await api('/auth/v1/signup',{method:'POST',body:JSON.stringify({email,password})});if(data?.access_token){session={...data,expires_at:Math.floor(Date.now()/1000)+data.expires_in};localStorage.setItem(SESSION_KEY,JSON.stringify(session));logged=true;await pullCloud();render();toast('账号创建成功 ✓')}else{box.textContent='注册成功！请打开邮箱中的验证邮件，然后回来登录。';box.classList.remove('hidden');authMode='login';button.textContent='返回登录';button.onclick=()=>login()}}}catch(err){box.textContent=friendlyError(err);box.classList.remove('hidden');button.disabled=false;button.textContent=authMode==='login'?'登录':'免费注册'}}

function escapeHtml(s=''){return String(s).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function avatarHtml(cls='avatar'){return state.profile.avatar?`<div class="${cls}"><img src="${state.profile.avatar}" alt="${escapeHtml(state.profile.name)}的头像"></div>`:`<div class="${cls}">🐷</div>`}
function shell(){return `<div class="desktop"><div class="topbar"><div class="brand"><span class="brand-icon">🐷</span>小金库 2003</div><div class="today">今天是 2026年7月21日 · ${now()}</div></div><section class="window"><div class="titlebar"><span>📒 我的账本 - 小金库</span><div class="traffic"><span>─</span><span>□</span><span class="close">×</span></div></div><div class="menu"><button>文件(F)</button><button>编辑(E)</button><button>查看(V)</button><button>帮助(H)</button></div><div class="workspace"><aside class="sidebar"><div class="user-card">${avatarHtml()}<b>${escapeHtml(state.profile.name)}</b><small data-sync>在线 · ${syncStatus}</small></div><div class="nav">${navButtons()}</div><div class="side-tip">💡 本月提醒<br>先记账，再消费。你的每一笔月付都已经计入当月支出。</div></aside><main class="main">${content()}</main></div></section></div><footer class="taskbar"><button class="start">⊞ 开始</button><div class="task-tab">📒 小金库</div><div class="mobile-nav">${mobileNav()}</div><div class="clock">${now()}</div></footer>${modal?modalHtml():''}`}
function navButtons(){return [['home','🏠','首页'],['add','➕','记一笔'],['records','📋','明细'],['debts','⏰','待还款'],['budget','📊','预算'],['accounts','💳','账户'],['profile','👤','个人资料']].map(x=>`<button data-page="${x[0]}" class="${page===x[0]?'active':''}"><span>${x[1]}</span>${x[2]}</button>`).join('')+`<button id="logout"><span>🚪</span>退出登录</button>`}
function mobileNav(){return [['home','🏠','首页'],['add','➕','记账'],['records','📋','明细'],['debts','⏰','还款'],['accounts','💳','账户']].map(x=>`<button data-page="${x[0]}"><span>${x[1]}</span>${x[2]}</button>`).join('')}
function head(title,sub,action=''){return `<div class="page-head"><div><h1>${title}</h1><p>${sub}</p></div>${action}</div>`}
function content(){if(page==='add')return addPage();if(page==='records')return recordsPage();if(page==='debts')return debtsPage();if(page==='budget')return budgetPage();if(page==='accounts')return accountsPage();if(page==='profile')return profilePage();return homePage()}
function homePage(){const bal=Object.values(state.accounts).reduce((a,b)=>a+b,0), d=debt().reduce((s,t)=>s+t.amount,0);return `${head(`下午好，${escapeHtml(state.profile.name)} 👋`,'今天也要照顾好自己的钱包','<button class="primary" data-page="add">＋ 记一笔</button>')}<div class="cards"><div class="card"><span class="label">本月收入</span><div class="money">${money(income())}</div><span class="sub">${monthLabel()}累计</span></div><div class="card orange"><span class="label">本月花销</span><div class="money">${money(expense())}</div><span class="sub">含月付消费</span></div><div class="card ${remainingBudget()<0?'red':'green'}"><span class="label">本月剩余预算</span><div class="money">${money(remainingBudget())}</div><span class="sub">总预算 ${money(totalBudget())}</span></div><div class="card red"><span class="label">待还款</span><div class="money">${money(d)}</div><span class="sub">${debt().length} 笔待处理</span></div></div><div class="grid2"><section class="panel"><div class="panel-title"><span>📊 类别预算 · 剩余 ${money(remainingBudget())}</span><button class="secondary" data-page="budget">管理预算</button></div><div class="panel-body">${categories.slice(0,5).map(budgetLine).join('')}</div></section><section class="panel"><div class="panel-title"><span>📝 最近明细</span><button class="secondary" data-page="records">查看全部</button></div><div class="panel-body">${state.transactions.slice(0,5).map(txLine).join('')}</div></section></div>`}
function budgetLine(c){let u=used(c),b=Number(state.budgets[c]),left=b-u,p=Math.min(100,u/b*100||0);return `<div class="budget-row"><div class="row-top"><span>${icons[c]} ${c}</span><span class="${left<0?'budget-over':''}">剩余 ${money(left)}</span></div><div class="track"><div class="fill ${p>80?'warn':''}" style="width:${p}%"></div></div><div class="budget-meta">已用 ${money(u)} / 预算 ${money(b)}</div></div>`}
function txLine(t){return `<div class="tx"><span class="tx-icon">${t.type==='income'?'💰':icons[t.category]||'💵'}</span><span><b>${t.note||t.category}</b><small>${t.date.slice(5)} ${t.time} · ${t.platform}${!t.repaid?' · 待还款':''}</small></span><span class="tx-amount ${t.type==='income'?'in':''}">${t.type==='income'?'+':'−'}${money(t.amount)}</span></div>`}
function addPage(){return `${head('记一笔','日期与时间会自动填充')}<section class="panel"><div class="panel-title">✏️ 新增记录</div><div class="panel-body"><form id="txForm"><div class="choice" id="typeChoice"><button type="button" class="selected" data-value="expense">花销</button><button type="button" data-value="income">收入</button></div><div class="form-grid" style="margin-top:14px"><div class="field full"><label>金额</label><input class="amount-input" id="amount" type="number" min="0.01" step="0.01" placeholder="¥ 0.00" required></div><div class="field full" id="catField"><label>类别</label><div class="choice" id="catChoice">${categories.map((c,i)=>`<button type="button" data-value="${c}" class="${i===0?'selected':''}">${icons[c]} ${c}</button>`).join('')}</div></div><div class="field"><label>日期</label><input id="date" type="date" value="${today()}"></div><div class="field"><label>时间</label><input id="time" type="time" value="${new Date().toTimeString().slice(0,5)}"></div><div class="field full"><label>支付平台 / 入账账户</label><div class="choice" id="platformChoice">${['微信','支付宝','美团月付','抖音月付','银行卡'].map((c,i)=>`<button type="button" data-value="${c}" class="${i===0?'selected':''}">${c}</button>`).join('')}</div></div><div class="field full"><label>备注</label><textarea id="note" rows="3" placeholder="写点什么（可选）"></textarea></div></div><div class="form-actions"><button type="reset" class="secondary">清空</button><button class="primary">保存记录</button></div></form></div></section>`}
function recordsPage(){let list=monthTx();return `${head('收支明细','每一笔都清清楚楚','<button class="primary" data-page="add">＋ 记一笔</button>')}<section class="panel"><div class="panel-title"><span>📋 ${monthLabel()}</span><span>共 ${list.length} 笔</span></div><div class="panel-body">${list.length?list.map(txLine).join(''):'<div class="empty">本月还没有记录</div>'}</div></section>`}
function debtsPage(){let groups=['美团月付','抖音月付'];return `${head('待还款','还款只扣账户余额，不会重复计入花销')}<div class="notice">🔔 <span><b>还款提醒：每月 10–15 日</b><br>勾选之前的消费记录，选择扣款账户后即可一键还款。</span></div><div style="height:14px"></div>${groups.map(g=>{let list=debt().filter(t=>t.platform===g),sum=list.reduce((s,t)=>s+t.amount,0);return `<section class="panel debt-group"><div class="debt-head"><b>${g}</b><b>${money(sum)}</b></div>${list.length?list.map(t=>`<label class="check-row"><input type="checkbox" data-debt="${t.id}" ${selectedDebt.has(t.id)?'checked':''}><span><b>${t.note||t.category}</b><small>${t.date} · ${t.category}</small></span><b>${money(t.amount)}</b></label>`).join(''):'<div class="empty">🎉 暂无待还款</div>'}</section>`}).join('')}<div class="form-actions"><span style="margin-right:auto">已选 ${selectedDebt.size} 笔</span><button class="primary" id="repayBtn" ${selectedDebt.size?'':'disabled'}>一键还款</button></div>`}
function budgetPage(){return `${head('类别预算','预算按月计算，每笔花销都会扣减对应类别的剩余预算')}<div class="cards budget-summary"><div class="card"><span class="label">月总预算</span><div class="money">${money(totalBudget())}</div></div><div class="card orange"><span class="label">本月已用</span><div class="money">${money(expense())}</div></div><div class="card ${remainingBudget()<0?'red':'green'}"><span class="label">本月剩余</span><div class="money">${money(remainingBudget())}</div></div></div><section class="panel"><div class="panel-title"><span>📊 ${monthLabel()}预算</span><span>修改各类别上限</span></div><div class="panel-body"><div class="account-list">${categories.map(c=>{let left=Number(state.budgets[c])-used(c);return `<div class="account"><span>${icons[c]} <b>${c}</b><small class="${left<0?'budget-over':''}" style="display:block">已用 ${money(used(c))} · 剩余 ${money(left)}</small></span><span><input data-budget="${c}" type="number" min="0" step="1" value="${state.budgets[c]}" style="width:100px;padding:7px"> 元</span></div>`}).join('')}</div><div class="form-actions"><button class="primary" id="saveBudget">保存预算</button></div></div></section>`}
function accountsPage(){let total=Object.values(state.accounts).reduce((a,b)=>a+b,0);return `${head('账户与存款','管理你的真实可用余额')}<div class="cards"><div class="card"><span class="label">账户总余额</span><div class="money">${money(total)}</div></div><div class="card green"><span class="label">累计存款</span><div class="money">${money(state.savings)}</div></div><div class="card orange"><span class="label">本月结余</span><div class="money">${money(income()-expense())}</div></div><div class="card red"><span class="label">待还负债</span><div class="money">${money(debt().reduce((s,t)=>s+t.amount,0))}</div></div></div><section class="panel"><div class="panel-title">💳 我的账户</div><div class="panel-body"><form id="accountsForm"><div class="account-list">${Object.entries(state.accounts).map(([k,v])=>`<label class="account account-edit"><span>${k==='微信'?'🟢':k==='支付宝'?'🔵':'🏦'} <b>${k}余额</b></span><span class="balance-input"><span>¥</span><input data-account="${k}" aria-label="${k}余额" type="number" min="0" step="0.01" value="${Number(v).toFixed(2)}" required></span></label>`).join('')}</div><div class="notice" style="margin-top:14px">💡 手动修改用于校准实际余额，不会被计入收入或花销。月末结余仍按收入减去全部花销计算。</div><div class="form-actions"><button class="primary">保存账户余额</button></div></form></div></section>`}
function profilePage(){return `${head('个人资料','设置在账本中显示的用户名和头像')}<section class="panel"><div class="panel-title">👤 我的名片</div><div class="panel-body"><form id="profileForm"><div class="profile-editor"><div class="avatar-picker">${avatarHtml('avatar avatar-large')}<label class="secondary upload-button" for="avatarInput">📷 从相册选择</label><input id="avatarInput" type="file" accept="image/jpeg,image/png,image/webp,image/heic,image/heif" hidden><button type="button" class="secondary ${state.profile.avatar?'':'hidden'}" id="removeAvatar">恢复默认头像</button><small>支持 JPG、PNG、WebP 和 iPhone 相册图片，建议小于 5MB</small></div><div class="field"><label for="profileName">用户名</label><input id="profileName" maxlength="20" value="${escapeHtml(state.profile.name)}" placeholder="请输入用户名" required><small>最多 20 个字符</small></div></div><div class="form-actions"><button class="primary">保存个人资料</button></div></form></div></section>`}
function modalHtml(){if(modal==='repay')return `<div class="modal-wrap"><div class="modal"><div class="titlebar"><span>💳 确认还款</span><div class="traffic"><span class="close" id="closeModal">×</span></div></div><div class="body"><p>选择扣款账户：</p><div class="choice" id="repayAccount">${Object.entries(state.accounts).map(([k,v],i)=>`<button data-value="${k}" class="${i===0?'selected':''}">${k} · ${money(v)}</button>`).join('')}</div><div class="form-actions"><button class="secondary" id="cancelModal">取消</button><button class="primary" id="confirmRepay">确认还款</button></div></div></div></div>`;return ''}

function render(){if(!logged)return login();app.innerHTML=shell();bind()}
function selectIn(container,cb){document.querySelectorAll(`${container} button`).forEach(b=>b.onclick=()=>{document.querySelectorAll(`${container} button`).forEach(x=>x.classList.remove('selected'));b.classList.add('selected');cb?.(b.dataset.value)})}
function bind(){document.querySelectorAll('[data-page]').forEach(b=>b.onclick=()=>{page=b.dataset.page;render()});document.querySelector('#logout')?.addEventListener('click',async()=>{if(!demoMode){try{await api('/auth/v1/logout',{method:'POST'})}catch{}}session=null;demoMode=false;logged=false;localStorage.removeItem(SESSION_KEY);render()});
  if(page==='add'){let type='expense';selectIn('#typeChoice',v=>{type=v;document.querySelector('#catField').classList.toggle('hidden',v==='income')});selectIn('#catChoice');selectIn('#platformChoice');document.querySelector('#txForm').onsubmit=e=>{e.preventDefault();let amount=Number(document.querySelector('#amount').value),platform=document.querySelector('#platformChoice .selected').dataset.value,cat=type==='income'?'收入':document.querySelector('#catChoice .selected').dataset.value,repaid=!(platform==='美团月付'||platform==='抖音月付');state.transactions.unshift({id:Date.now(),type,amount,category:cat,platform,date:document.querySelector('#date').value,time:document.querySelector('#time').value,note:document.querySelector('#note').value,repaid});if(repaid){state.accounts[platform]=(state.accounts[platform]||0)+(type==='income'?amount:-amount)}save();page='home';render();toast('记录已保存 ✓')}}
  if(page==='debts'){document.querySelectorAll('[data-debt]').forEach(c=>c.onchange=()=>{let id=Number(c.dataset.debt);c.checked?selectedDebt.add(id):selectedDebt.delete(id);render()});document.querySelector('#repayBtn')?.addEventListener('click',()=>{modal='repay';render()})}
  if(page==='budget')document.querySelector('#saveBudget').onclick=()=>{document.querySelectorAll('[data-budget]').forEach(i=>state.budgets[i.dataset.budget]=Number(i.value));save();render();toast('预算已更新 ✓')}
  if(page==='accounts')document.querySelector('#accountsForm').onsubmit=e=>{e.preventDefault();document.querySelectorAll('[data-account]').forEach(i=>state.accounts[i.dataset.account]=Number(i.value));save();render();toast('账户余额已保存并同步 ✓')}
  if(page==='profile'){let pendingAvatar=state.profile.avatar;document.querySelector('#avatarInput').onchange=e=>{let file=e.target.files?.[0];if(!file)return;if(file.size>8*1024*1024){toast('图片不能超过 8MB');e.target.value='';return}let reader=new FileReader();reader.onload=()=>{let img=new Image();img.onload=()=>{let size=256,canvas=document.createElement('canvas');canvas.width=size;canvas.height=size;let ctx=canvas.getContext('2d'),side=Math.min(img.width,img.height),sx=(img.width-side)/2,sy=(img.height-side)/2;ctx.drawImage(img,sx,sy,side,side,0,0,size,size);pendingAvatar=canvas.toDataURL('image/jpeg',.82);let box=document.querySelector('.avatar-large');box.innerHTML=`<img src="${pendingAvatar}" alt="头像预览">`;document.querySelector('#removeAvatar').classList.remove('hidden')};img.onerror=()=>toast('无法读取这张图片，请尝试 JPG 或 PNG');img.src=reader.result};reader.readAsDataURL(file)};document.querySelector('#removeAvatar')?.addEventListener('click',()=>{pendingAvatar='';document.querySelector('.avatar-large').innerHTML='🐷';document.querySelector('#removeAvatar').classList.add('hidden')});document.querySelector('#profileForm').onsubmit=e=>{e.preventDefault();let name=document.querySelector('#profileName').value.trim();if(!name)return;state.profile={name,avatar:pendingAvatar};save();render();toast('个人资料已保存并同步 ✓')}}
  if(modal){selectIn('#repayAccount');let close=()=>{modal=null;render()};document.querySelector('#closeModal').onclick=close;document.querySelector('#cancelModal').onclick=close;document.querySelector('#confirmRepay').onclick=()=>{let acc=document.querySelector('#repayAccount .selected').dataset.value,total=0;state.transactions.forEach(t=>{if(selectedDebt.has(t.id)){t.repaid=true;total+=t.amount}});state.accounts[acc]-=total;selectedDebt.clear();modal=null;save();render();toast(`还款 ${money(total)} 成功 ✓`)}}
}
function toast(msg){let el=document.createElement('div');el.className='toast';el.textContent=msg;document.body.append(el);setTimeout(()=>el.remove(),3200)}
async function bootstrap(){if(session?.refresh_token&&session.expires_at<Date.now()/1000+60){try{let data=await api('/auth/v1/token?grant_type=refresh_token',{method:'POST',body:JSON.stringify({refresh_token:session.refresh_token})});session={...data,expires_at:Math.floor(Date.now()/1000)+data.expires_in};localStorage.setItem(SESSION_KEY,JSON.stringify(session))}catch{session=null;logged=false;localStorage.removeItem(SESSION_KEY)}}if(session){try{await pullCloud();syncStatus='已同步'}catch(e){syncStatus='同步失败';setTimeout(()=>toast(`云同步失败：${friendlyError(e)}`),100)}}render()}
bootstrap()
